version: 2

references:

  xcode_version: &xcode_version
    xcode: 11.1.0

  ## Install Steps

  install_golang: &install_golang
    run:
      name: Install Golang
      command: .circleci/install/golang.sh

  install_dots: &install_dots
    run:
      name: Installing Dots
      command: go get -u github.com/drn/dots

  ## Cache

  cache_brew: &cache_brew
    save_cache:
      name: Cache Homebrew
      key: v1-brew-{{ .Branch }}-{{ .Revision }}
      paths:
        - /usr/local/Homebrew

  restore_brew: &restore_brew
    restore_cache:
      name: Restore Homebrew
      keys:
        - v1-brew-{{ .Branch }}-{{ .Revision }}
        - v1-brew-{{ .Branch }}
        - v1-brew

  cache_go: &cache_go
    save_cache:
      name: Cache $GOPATH
      key: v1-go-{{ .Branch }}-{{ .Revision }}
      paths:
        - ~/go

  restore_go: &restore_go
    restore_cache:
      name: Restore $GOPATH
      keys:
        - v1-go-{{ .Branch }}-{{ .Revision }}

  ## General

  setup_path: &setup_path
    run:
      name: Setting Up $PATH
      command: |
        echo 'export PATH=$HOME/go/bin:$PATH' >> $BASH_ENV

  ## Step Wrappers

  dots_steps: &dots_steps
    steps:
      - checkout
      - *restore_brew
      - *restore_go
      - *setup_path
      - run:
          name: Running Command
          command: eval $COMMAND
          no_output_timeout: 30m

jobs:
  build:
    macos:
      *xcode_version
    steps:
      - checkout
      - *restore_brew
      - run:
          name: Brew Update
          command: |
            rm -rf /usr/local/Homebrew/Library/Taps
            brew update
      - *cache_brew
      - *install_golang
      - *install_dots
      - *cache_go
      - run:
          name: Running Dots Root
          command: dots

  install-bin:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install bin'
    <<: *dots_steps

  install-git:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install git'
    <<: *dots_steps

  install-home:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install home'
    <<: *dots_steps

  install-zsh:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install zsh'
    <<: *dots_steps

  install-fonts:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install fonts'
    <<: *dots_steps

  install-homebrew:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install homebrew'
    <<: *dots_steps

  install-npm:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install npm'
    <<: *dots_steps

  install-vim:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install vim'
    <<: *dots_steps

  install-python:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install python'
    <<: *dots_steps

  install-ruby:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install ruby'
    <<: *dots_steps

  install-hammerspoon:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install hammerspoon'
    <<: *dots_steps

  install-osx:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots install osx'
    <<: *dots_steps

  update:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots update'
    <<: *dots_steps

  cleanup:
    macos:
      *xcode_version
    environment:
      COMMAND: 'dots cleanup'
    <<: *dots_steps

  ruby-lint:
    machine: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Gemfile Cache
          keys:
            - v1-gems-{{ checksum "Gemfile.lock" }}
            - v1-gems
      - run:
          name: Install Gemfile Dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          name: Save Gemfile Cache
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Ruby Lint
          command: bundle exec rubocop

  go-lint:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Golint
          command: go get -u golang.org/x/lint/golint
      - run:
          name: Go Lint
          command: golint ./...

workflows:
  version: 2
  build:
    jobs:
      - build
      - ruby-lint
      - go-lint
      - install-bin:
          requires:
            - build
      - install-git:
          requires:
            - build
      - install-home:
          requires:
            - build
      - install-zsh:
          requires:
            - build
      - install-fonts:
          requires:
            - build
      - install-homebrew:
          requires:
            - build
      - install-npm:
          requires:
            - build
      - install-vim:
          requires:
            - build
      - install-python:
          requires:
            - build
      - install-ruby:
          requires:
            - build
      - install-hammerspoon:
          requires:
            - build
      - install-osx:
          requires:
            - build
      - update:
          requires:
            - build
      - cleanup:
          requires:
            - build
